from django.urls import path
import LearnApp.views
urlpatterns=[
    path('',LearnApp.views.home,name='index'),
    path('news', LearnApp.views.news, name='news'),
    path('aboutpage',LearnApp.views.aboutpage,name='aboutpage'),
    path('login',LearnApp.views.login,name='login'),
    path('add_blog',LearnApp.views.add_blog,name='add_blog'),
    path('display_blog', LearnApp.views.display_blog, name='display_blog'),
    path('contact', LearnApp.views.contact, name='contact'),
    path('register_teacher', LearnApp.views.register_teacher, name='register_teacher'),
    path('register_student', LearnApp.views.register_student, name='register_student'),
    path('register_admin', LearnApp.views.register_admin, name='register_admin'),
    path('admin', LearnApp.views.admin, name='admin'),
    path('teacher_home', LearnApp.views.teacher_home, name='teacher_home'),
    path('admin_home', LearnApp.views.admin_home, name='admin_home'),
    path('admin_profile',LearnApp.views.adm_prof, name='adm_prof'),
    path('blogs_admin', LearnApp.views.blogs_admin, name='blogs_admin'),
    path('upload_cer', LearnApp.views.upload_cer, name='upload_cer'),
    path('del_cer', LearnApp.views.del_cer, name='del_cer'),
    path('delete_cer/<id>', LearnApp.views.delete_cer, name='delete_cer'),

    path('about_content', LearnApp.views.about_content, name='about_content'),
    path('block', LearnApp.views.block, name='block'),
    path('feedback', LearnApp.views.feedback, name='feedback'),
    path('pass_req', LearnApp.views.pass_req, name='pass_req'),

    path('member_message', LearnApp.views.member_message, name='member_message'),
    path('sent_msg_admin', LearnApp.views.sent_msg_admin, name='sent_msg_admin'),
    path('del_msg_admin/<id>', LearnApp.views.del_msg_admin, name='del_msg_admin'),
    path('reply_msg_admin/<id>', LearnApp.views.reply_msg_admin, name='reply_msg_admin'),
    path('guest_message', LearnApp.views.guest_message, name='guest_message'),
    path('delete_guest_msg/<id>', LearnApp.views.delete_guest_msg, name='delete_guest_msg'),

    path('admin_sub_edit/<s_edit>', LearnApp.views.admin_sub_edit, name='admin_sub_edit'),
    path('admin_subject_view', LearnApp.views.admin_subject_view, name='admin_subject_view'),
    path('admin_sub_delete/<s_delete>', LearnApp.views.admin_sub_delete, name='admin_sub_delete'),
    path('chapter_add', LearnApp.views.chap_ad, name='chap_ad'),
    path('content_add', LearnApp.views.cont_ad, name='cont_ad'),
    path('admin_approve/<apr>', LearnApp.views.admin_approve, name='admin_approve'),
    path('admin_reject/<rej>', LearnApp.views.admin_reject, name='admin_reject'),
    path('admin_delete/<delt>', LearnApp.views.admin_delete, name='admin_delete'),
    path('logout',LearnApp.views.logout, name='logout'),
    path('tec_update_pro', LearnApp.views.tec_update_pro, name='tec_update_pro'),
    path('tec_stud_prog', LearnApp.views.tec_stud_prog, name='tec_stud_prog'),
    path('tec_chnge_passwrd', LearnApp.views.tec_chnge_passwrd, name='tec_chnge_passwrd'),
    path('tec_courses', LearnApp.views.tec_courses, name='tec_courses'),
    path('tec_chapter', LearnApp.views.tec_chapter, name='tec_chapter'),
    path('tec_cont', LearnApp.views.tec_cont, name='tec_cont'),
    path('tec_edit_cont/<id>', LearnApp.views.tec_edit_cont, name='tec_edit_cont'),
    path('tec_delete_cont/<id>', LearnApp.views.tec_delete_cont,name='tec_delete_cont'),
    path('tec_add_chapter_content', LearnApp.views.tec_add_chapter_content,name='tec_add_chapter_content'),
    path('tec_add_chapter_c0', LearnApp.views.tec_add_chapter_c0, name = 'tec_add_chapter_c0'),
    path('tec_add_chapter_c1', LearnApp.views.tec_add_chapter_c1, name = 'tec_add_chapter_c1'),
    path('course_edit/<c_edit>', LearnApp.views.course_edit, name='course_edit'),
    path('course_add', LearnApp.views.course_add, name='course_add'),
    path('course_delete/<c_delete>', LearnApp.views.course_delete, name='course_delete'),
    path('tec_chapter', LearnApp.views.tec_chapter, name='tec_chapter'),
    path('tec_add_chapter', LearnApp.views.tec_add_chapter, name='tec_add_chapter'),
    path('tec_edit_chapter/<id><idd><idk><idm>', LearnApp.views.tec_edit_chapter, name='tec_edit_chapter'),
    path('tec_delete_chapter/<id><idd><idk><idm>', LearnApp.views.tec_delete_chapter, name='tec_delete_chapter'),

    path('tec_st_booked', LearnApp.views.tec_st_booked, name='tec_st_booked'),
    path('stu_accept/<id>', LearnApp.views.stu_accept, name='stu_accept'),
    path('stu_reject/<id>', LearnApp.views.stu_reject, name='stu_reject'),
    path('stu_delete/<id>', LearnApp.views.stu_delete, name='stu_delete'),

    path('tec_sh_test', LearnApp.views.tec_sh_test, name='tec_sh_test'),
    path('tec_sh_test1', LearnApp.views.tec_sh_test1, name='tec_sh_test1'),
    path('tec_sh_test2', LearnApp.views.tec_sh_test2, name='tec_sh_test2'),

    path('tec_de_test', LearnApp.views.tec_de_test, name='tec_de_test'),
    path('tec_de_test1/<id>', LearnApp.views.tec_de_test1, name='tec_de_test1'),

    path('tec_exm_result', LearnApp.views.tec_exm_result, name='tec_exm_result'),
    path('tec_exam_result_del/<id>', LearnApp.views.tec_exam_result_del, name='tec_exam_result_del'),

    path('tec_message', LearnApp.views.tec_message, name='tec_message'),
    path('tec_sent_msg', LearnApp.views.tec_sent_msg, name='tec_sent_msg'),
    path('tec_reply_msg/<id>', LearnApp.views.tec_reply_msg, name='tec_reply_msg'),
    path('tec_del_msg/<id>', LearnApp.views.tec_del_msg, name='tec_del_msg'),

    path('tec_attendence', LearnApp.views.tec_attendence, name='tec_attendence'),
    path('t_allow/<t_alw>', LearnApp.views.t_allow, name='t_allow'),
    path('t_block/<t_blk>', LearnApp.views.t_block, name='t_block'),
    path('s_allow/<s_alw>', LearnApp.views.s_allow, name='s_allow'),
    path('s_block/<s_blk>', LearnApp.views.s_block, name='s_block'),
    path('feed_delete/<feed>', LearnApp.views.feed_delete, name='feed_delete'),


    #student_area
    path('student_home', LearnApp.views.student_home, name='student_home'),
    path('stu_booked_courses', LearnApp.views.stu_booked_courses, name='stu_booked_courses'),
    path('stu_access_chapter/<id>', LearnApp.views.stu_access_chapter, name='stu_access_chapter'),
    path('stu_access_chapter1>', LearnApp.views.stu_access_chapter1, name='stu_access_chapter1'),
    path('compp', LearnApp.views.compp, name='compp'),
    path('stu_book_course', LearnApp.views.stu_book_course, name='stu_book_course'),
    path('stu_book_course_c0', LearnApp.views.stu_book_course_c0,name='stu_book_course_c0'),
    path('stu_book_course_c1', LearnApp.views.stu_book_course_c1, name='stu_book_course_c1'),
    path('stu_book_course_c2/<f>/<m>', LearnApp.views.stu_book_course_c2, name='stu_book_course_c2'),
    path('stu_change_pwd', LearnApp.views.stu_change_pwd, name='stu_change_pwd'),
    path('stu_down_cert', LearnApp.views.stu_down_cert, name='stu_down_cert'),
    path('stu_exam_notify', LearnApp.views.stu_exam_notify, name='stu_exam_notify'),
    path('stu_exam_result', LearnApp.views.stu_exam_result, name='stu_exam_result'),
    path('stu_feedback', LearnApp.views.stu_feedback, name='stu_feedback'),
    path('stu_message', LearnApp.views.stu_message, name='stu_message'),
    path('stu_sent_msg',LearnApp.views.stu_sent_msg, name='stu_sent_msg'),
    path('stu_reply_msg/<id>', LearnApp.views.stu_reply_msg, name='stu_reply_msg'),
    path('stu_del_msg/<id>', LearnApp.views.stu_del_msg, name='stu_del_msg'),
    path('stu_start_test', LearnApp.views.stu_start_test, name='stu_start_test'),
    path('save_exam', LearnApp.views.save_exam, name= 'save_exam'),
    path('stu_update_pro', LearnApp.views.stu_update_pro, name='stu_update_pro'),

]