# Generated by Django 3.1.3 on 2020-12-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnApp', '0002_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning_progress',
            name='Teacher_email',
            field=models.EmailField(max_length=254),
            preserve_default=False,
        ),
    ]
